version: "3"
services:
  app:
    container_name: spokat_shop_app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/app
      - vendor_app:/var/www/app/vendor
      - ./docker/99-upload-config.ini:/usr/local/etc/php/conf.d/99-upload-config.ini
    depends_on:
      - db
    networks:
      - spokat_shop
  db:
    container_name: spokat_shop_db
    image: postgres:13.9-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-spokat_shop}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ${POSTGRES_VOLUME:-./docker/postgres}:/var/lib/postgresql/data
    ports:
      - "${FORWARD_POSTGRES_PORT:-54320}:5432"
    networks:
      - spokat_shop
  nginx:
    container_name: spokat_shop_nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - '${FORWARD_NGINX_PORT:-8080}:80'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./:/var/www/app
    depends_on:
      - app
    networks:
      - spokat_shop
networks:
  spokat_shop:
    driver: bridge
    
volumes:
  vendor_app:  
  
